Models/AdminViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CargoManagement.Admin.Models
{
    public class AdminViewModel
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage ="Please Provide User Name")]
        [Display(Name="User Name")]
        public string UserName { get; set; }

        public string? Name { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [DefaultValue("Admin@123")]

        public string Password { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace CargoManagement.Admin.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AdminsController.cs
using CargoManagement.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace CargoManagement.Admin.Controllers
{
    public class AdminsController : Controller
    {
        //private readonly string ApiUrl = "https://localhost:44333/api/";
        private readonly IConfiguration _configuration;
        public AdminsController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> Index()
        {
            List<AdminViewModel> admins = new();
            using(var client=new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync("Admins/GetAllAdmin");
                if (result.IsSuccessStatusCode)
                {
                    admins = await result.Content.ReadAsAsync<List<AdminViewModel>>();
                }
                
            }
            return View(admins);
        }
        public async Task<IActionResult> Details(int id)
        {
            AdminViewModel admin = null;
            using(var client=new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync($"Admins/GetAdminById/{id}");
                if (result.IsSuccessStatusCode)
                {
                    admin = await result.Content.ReadAsAsync<AdminViewModel>();
                }
            }
            return View(admin);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AdminViewModel admin)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                    var result = await client.PostAsJsonAsync("Admins/CreateAdmin", admin);
                    if (result.StatusCode == System.Net.HttpStatusCode.Created)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return View(admin);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (ModelState.IsValid)
            {
                AdminViewModel admin = null;
                using(var client=new HttpClient())
                {
                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                    var result = await client.GetAsync($"Admins/GetAdminById/{id}");
                    if (result.IsSuccessStatusCode)
                    {
                        admin = await result.Content.ReadAsAsync<AdminViewModel>();
                        return View(admin);
                    }
                    else
                    {
                        ModelState.AddModelError("", "Admin Doesn't Exist");
                    }
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AdminViewModel admin)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                    var result = await client.PutAsJsonAsync($"Admins/UpdateAdmin/{admin.Id}", admin);
                    if (result.StatusCode == System.Net.HttpStatusCode.NoContent)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Server Error. Please try later");
                    }
                }
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            AdminViewModel admin = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_configuration["ApiUrl:api"]);
                var result = await client.GetAsync($"Admins/GetAdminById/{id}");
                if (result.IsSuccessStatusCode)
                {
                    admin = await result.Content.ReadAsAsync<AdminViewModel>();
                }
            }
            return View(admin);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(AdminViewModel admin)
        {
            using(var client=new HttpClient())
            {
                client.BaseAddress = new System.Uri(_configuration["ApiUrl:api"]);
                var result = await client.DeleteAsync($"Admins/DeleteAdmin/{admin.Id}");
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Server Error. Please try Later");
                }
            }
            return View();
        }
    }
}

Controllers/HomeController.cs
using CargoManagement.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CargoManagement.Admin.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Admins/Create.cshtml
@model AdminViewModel
@{
    ViewData["Title"] = "Create";
}

<h1>Create an Admin</h1>

<form asp-controller="Admins" asp-action="Create" method="post">
    <div class="row">
        <div class="col-md-5">
            <div class="mb-2">
                <label asp-for="UserName"></label>
                <input type="text" asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName"></span>
            </div>
            <div class="mb-2">
                <label asp-for="Name"></label>
                <input type="text" asp-for="Name" class="form-control" />
                <span asp-validation-for="Name"></span>
            </div>
            <div class="mb-2">
                <label asp-for="Email"></label>
                <input type="email" asp-for="Email" class="form-control" />
                <span asp-validation-for="Email"></span>
            </div>
            <div class="mb-2">
                <label asp-for="Password"></label>
                <input type="password" asp-for="Password" class="form-control" />
                <span asp-validation-for="Password"></span>
            </div>
            <div class="mt-2">
                <input type="submit" class="btn btn-primary" value="Add New" />
            </div>
        </div>
    </div>
</form>

Views/Admins/Delete.cshtml
@model AdminViewModel
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Admin Details</h1>

<div class="row">
    <div class="col-md-5">
        <div asp-validation-summary="All"class="text-danger"></div>
        <ul class="list-group">
            <li class="list-group-item"><b>Author Name:</b>@Model.Name</li>
            <li class="list-group-item"><b>Email:</b>@Model.Email</li>
            <li class="list-group-item"><b>User Name:</b>@Model.UserName</li>
            <li class="list-group-item"><b>Password:</b>@Model.Password</li>

        </ul>
        <div>
            Are you sure Do you want to Delete this Admin?
        </div>
        <div>
            <form asp-controller="Admins" asp-action="Delete" method="post">
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </div>
        <a asp-controller="Admins" asp-action="Index">Back to List</a>
    </div>
</div>

Views/Admins/Details.cshtml
@model AdminViewModel 
@{
    ViewData["Title"] = "Details";
}

<h1>Admin Details</h1>
<div class="row">
    <div class="col-md-5">
        <ul class="list-group">
            <li class="list-group-item"><b>Author Name:</b>@Model.Name</li>
            <li class="list-group-item"><b>Email:</b>@Model.Email</li>
            <li class="list-group-item"><b>User Name:</b>@Model.UserName</li>
            <li class="list-group-item"><b>Password:</b>@Model.Password</li>

        </ul>
        <a asp-controller="Admins" asp-action="Index">Back to List</a>
    </div>
</div>

Views/Admins/Edit.cshtml
@model AdminViewModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Admin</h1>

<form asp-controller="Admins" asp-action="Edit" method="post">
    <div class="row">
        <div class="col-md-4">
            <div asp-validation-summary="All"class="text-danger"></div>
            <div class="mb-2">
                <label asp-for="UserName"></label>
                <input type="text" asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName"></span>
            </div>
            <div class="mb-2">
                <label asp-for="Name"></label>
                <input type="text" asp-for="Name" class="form-control" />
                <span asp-validation-for="Name"></span>
            </div>
            <div class="mb-2">
                <label asp-for="Email"></label>
                <input type="email" asp-for="Email" class="form-control" />
                <span asp-validation-for="Email"></span>
            </div>
            <div class="mb-2">
                <label asp-for="Password"></label>
                <input type="password" asp-for="Password" class="form-control" />
                <span asp-validation-for="Password"></span>
            </div>
            <div class="mt-2">
                <input type="submit" class="btn btn-primary" value="Add New" />
            </div>
        </div>
    </div>
</form>

Views/Admins/Index.cshtml
@model IEnumerable<AdminViewModel>
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-md-7">
        <div class="row">
            <div class="col">
                <h2>List of Admins</h2>
            </div>
            <div class="col text-end">
                <a asp-controller="Admins" asp-action="Create" class="btn btn-warning" >Create New Admin</a>
            </div>
        </div>
        <div class="row">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>UserName</th>
                    <th>Name</th>
                    <th>email</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.UserName</td>
                        <td>@item.Name</td>
                        <td>@item.Email</td>
                        <td>
                            <a asp-controller="Admins" asp-action="Details" asp-route-id="@item.Id">Details</a>|
                            <a asp-controller="Admins" asp-action="Edit" asp-route-id="@item.Id">Edit</a>|
                            <a asp-controller="Admins" asp-action="Delete" asp-route-id="@item.Id">Delete</a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
            </div>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CargoManagement.Admin</title>
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CargoManagement.Admin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admins" asp-action="Index">Admin</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CargoManagement.Admin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/jquery/jquery.min.js"></script>
    <script src="~/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>